### ISSUE TITLE
Please support http

### ISSUE THREAD

**Issue by tsuwatch** [r7kamura/ruboty-github#21]
I want to use http (GITHUB_HOST)
https://github.com/r7kamura/ruboty-github/blob/master/lib/ruboty/github/actions/base.rb#L60

**Comment by r7kamura** [comment]
@tsuwatch Thanks for issueing, that makes sence. We might want to change `GITHUB_HOST` with `GITHUB_BASE_URL` instead. Unfortunately I can't test it because I'm no longer using GitHub Enterprise now. Can you make a pull-request for it?

**Comment by tsuwatch** [comment]
Thanks :pray:
